### ISSUE TITLE
Shader error

### ISSUE THREAD

**Issue by vjeux** [pyalot/craftscape#1]
```
water/display.shader: program link: undefined: Shader@0x0480AB48(209,9): warning X3206: implicit truncation of vector type
Shader@0x0480AB48(182,21): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
Vertex shader sampler count exceeds MAX_VERTEX_TEXTURE_IMAGE_UNITS (4).
```

I'm using Chrome 15.0.874.106 m on Windows

**Comment by pyalot** [comment]
You can try running chrome with --use-gl=desktop . Otherwise I can't do much about this bug, because my shader doesn't use 4 units, I did test that the units where available before, if you indeed have less then 4 units, you can't run my demo, and if you have more then 4 units then it's a Chrome, Angleproject, Direct3D, Windows, Nvidia/ATI bug and I'd encourage you to file bugs in each respective helpdesk/issue tracker.
